name: romanovska
favicon: null
layout_spectrum: 0.50395
typography_spectrum: 0.9938728772103786
title: Anna Romanovska UX designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.23564446880482137
purpose: []
