name: romanovska
favicon: null
layout_spectrum: 0.74951
typography_spectrum: 0.9938728772103786
title: Anna Romanovska UX designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fb02fd'
    - '#2c779b'
    - '#000000'
    - '#ffffff'
    - '#f6a944'
  brandStrength: 0.47798093617893755
  lightness: 0.005981055786833167
  saturation: 0.7018554355017841
  rhythmicContrast: 0.23564446880482137
purpose: []
